/* DO NOT EDIT THIS FILE - it is machine generated */

#include "TCPconnect.h"
#include <android/log.h>

#include<stdio.h>
#include<sys/types.h>
#include<netinet/in.h>
#include<string.h>
#include<sys/socket.h>
#include<stdlib.h>
#include<unistd.h>

#define MAXLINE 1024
#define SIZE sizeof(struct sockaddr_in)
/* Header for class app_android_server_TCPconnect */

struct sockaddr_in sv_addr;
struct sockaddr_in cl_addr;
int sockfd_connect;
int sockfd_listen;
int port_num;

char errmsg[MAXLINE];

JNIEXPORT jint JNICALL Java_app_android_server_TCPConnect_listen_1server
(JNIEnv *env, jobject obj, jint port) {
	port_num = port;
	if((sockfd_listen = socket(AF_INET, SOCK_STREAM, 0)) == -1)
	{
		// listen socket make error
		return -1;
	}
    
	sv_addr.sin_family = AF_INET;
	sv_addr.sin_addr.s_addr = htonl(INADDR_ANY);
	sv_addr.sin_port = htons(port);
    
	if(bind(sockfd_listen, (struct sockaddr *)&sv_addr, SIZE) == -1)
	{
		// bind failed
		return -2;
	}

	if(listen(sockfd_listen, 1) == -1)
	{
		// listen error
		return -3;
	}

	return 0;
}

JNIEXPORT jstring JNICALL Java_app_android_server_TCPConnect_accept_1client
(JNIEnv *env, jobject obj) {
	char clientIP[MAXLINE];
	jstring clientIP_jstr;
	int addrlen = sizeof(cl_addr);

	if((sockfd_connect = accept(sockfd_listen, (struct sockaddr *)&cl_addr, &addrlen)) ==-1)
    {
		// accept error
		return NULL;
	}

	memset(clientIP, 0x00, MAXLINE);
	strcpy(clientIP, inet_ntoa(cl_addr.sin_addr));
	clientIP_jstr = (*env)->NewStringUTF(env, clientIP);
	return clientIP_jstr;
}

JNIEXPORT jint JNICALL Java_app_android_server_TCPConnect_send_1msg
(JNIEnv *env, jobject obj, jbyteArray img) {
	// no effect
	return 0;
}

JNIEXPORT jstring JNICALL Java_app_android_server_TCPConnect_recv_1msg
(JNIEnv *env, jclass jcls) {
	char content_recv[MAXLINE];
	int i;
	jstring str;

	memset(content_recv, 0x00, MAXLINE);
	i=recv(sockfd_connect,content_recv,MAXLINE,0);
	str = (*env)->NewStringUTF(env, content_recv);

	return str;
}

JNIEXPORT jint JNICALL Java_app_android_server_TCPConnect_close_1listenSocket
(JNIEnv *env, jobject obj) {
	close(sockfd_listen);
	return 0;
}

JNIEXPORT jint JNICALL Java_app_android_server_TCPConnect_close_1connectSocket
(JNIEnv *env, jobject obj) {
	close(sockfd_connect);
	return 0;
}