/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_android_server_TCPConnect */

#ifndef _Included_app_android_server_TCPConnect
#define _Included_app_android_server_TCPConnect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_android_server_TCPConnect
 * Method:    listen_server
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_app_android_server_TCPConnect_listen_1server
  (JNIEnv *, jobject, jint);

/*
 * Class:     app_android_server_TCPConnect
 * Method:    accept_client
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_android_server_TCPConnect_accept_1client
  (JNIEnv *, jobject);

/*
 * Class:     app_android_server_TCPConnect
 * Method:    send_msg
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_app_android_server_TCPConnect_send_1msg
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     app_android_server_TCPConnect
 * Method:    recv_msg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_app_android_server_TCPConnect_recv_1msg
  (JNIEnv *, jclass);

/*
 * Class:     app_android_server_TCPConnect
 * Method:    close_listenSocket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_server_TCPConnect_close_1listenSocket
  (JNIEnv *, jobject);

/*
 * Class:     app_android_server_TCPConnect
 * Method:    close_connectSocket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_server_TCPConnect_close_1connectSocket
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
