/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <linux/usbdevice_fs.h>
#include <memory.h>
#include <malloc.h>
#include <stdlib.h>

/* Header for class app_android_ltouchpad_UsbipMouse */
#ifndef _Included_app_android_ltouchpad_UsbipMouse
#define _Included_app_android_ltouchpad_UsbipMouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    connect_usbip
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_connect_1usbip
  (JNIEnv *, jobject);

/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    process_cmd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_process_1cmd
  (JNIEnv *, jobject);

/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    is_sendable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_is_1sendable
  (JNIEnv *, jobject);

/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    recv_ack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_recv_1ack
  (JNIEnv *, jobject);

/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    move
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_move
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    btn_left
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_btn_1left
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    btn_right
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_btn_1right
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    btn_scroll
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_btn_1scroll
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     app_android_ltouchpad_UsbipMouse
 * Method:    move_scroll
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_app_android_ltouchpad_UsbipMouse_move_1scroll
  (JNIEnv *, jobject, jint, jint);


int send_control();

void set_buffer_move(int x, int y, int scroll);

int set_buffer_btn(int left, int right, int scroll, int down);

void set_urb_control();

int send_cmd(int);

int send_urb(struct usbdevfs_urb *, unsigned char *);

int recv_seqnum(int, char*, int);

#ifdef __cplusplus
}
#endif
#endif
